_target_: src.models.motionencoder.mld_vae.MldVae

arch: 'encoder_decoder'
ff_size: 1024
num_layers: 9
num_heads: 4
dropout: 0.1
normalize_before: false
activation: 'gelu'
position_embedding: 'learned'
latent_dim: [1, 256]
#  nfeats: ${DATASET.NFEATS}
ablation:
  MLP_DIST: False
  SKIP_CONNECT: True
  PE_TYPE: mld
  DIFF_PE_TYPE: mld