_target_: src.datamodules.datasets.sampling.FrameSampler

# For fix size datamodule
request_frames: 40
threshold_reject: 0.75
sampling: conseq
sampling_step: 1

# For datamodule of any size
max_len: 10000
min_len: 10
