_target_: src.models.text_motion_model.TextMotionModel
generator:
  _target_: src.models.networks.mld_vae_net.MLDVae
  transforms: ${datamodule.transforms}
  vae: true
  loss_param_dict:
#    DIST_SYNC_ON_STEP: false
    stage: vae
#    LAMBDA_LATENT: 1.0e-5 # Lambda for latent Losses
#    LAMBDA_KL: 1.0e-4 # Lambda for kl Losses
#    LAMBDA_REC: 1.0 # Lambda for reconstruction Losses
#    LAMBDA_JOINT: 1.0 # Lambda for joint losses
#    LAMBDA_GEN: 1.0 # Lambda for text-motion generation losses
#    LAMBDA_CROSS: 1.0 # Lambda for reconstruction Losses
#    LAMBDA_CYCLE: 0.0 # Lambda for cycle Losses
#    LAMBDA_PRIOR: 0.0

losses:
  _target_: src.models.metrics.loss.ComputeLosses
  mode: smpl
  loss_dict:
    l_mldrecfeats: 1.0
    l_mldrecjoints: 1.0
    l_mldkl: 1.0e-4
  loss_opts:
    loss_feat_type: rfeats

#autoencoder_hidden_size: 384
#autoencoder_latent_size: 512
#droupout: 0.2
#activation: "LeakyReLU"

collate_fn: collate_datastruct_and_text

checkpoint_paths: ''

evaluator:
  _target_: src.utils.evaluator.Evaluator

do_evaluation: true

lr_args:
  gen_lr: 1e-8

defaults:
  - /model/motionencoder/mld_vae@generator.vae_model
  - /model/evaluator@evaluator


