_target_: src.models.multistage_text_motion_model.MultistageTextMotionModel
generator:
  _target_: src.models.networks.vq_diffusion.VQDiffusion
  transforms: ${datamodule.transforms}

autoencoder:
  _target_: src.models.networks.vq_vae_guo.VQVAEGuo
  transforms: ${datamodule.transforms}
  checkpoint_path: checkpoints/autoencoder_finest.tar

length_estimator:
  _target_: src.models.networks.guo_len_est.GuoLenEst
  checkpoint_path: ''

freeze_models_dict:
  generator: []
  autoencoder: [encoder, decoder, quant_conv, post_quant_conv, bottleneck_quantize]
  length_estimator: []

checkpoint_paths: checkpoints/text_motion_ddiff_best.ckpt

do_evaluation: false

devices: 'cpu'

defaults:
  - /model/textencoder/clip_text_embedding@generator.textencoder
  - /model/motionencoder/diffusion_transformer@generator.diffusion_model
  - /model/motionencoder/vq_encoder_v3_guo@autoencoder.encoder
  - /model/motiondecoder/vq_decoder_v3_guo@autoencoder.decoder
  - /model/motionencoder/quantizer_guo@autoencoder.quantizer
  - /model/textencoder/len_estimator_guo@length_estimator.textencoder