_target_: src.models.text_motion_model.TextMotionModel

generator:
  _target_: src.models.networks.vq_vae_guo.VQVAEGuo
  transforms: ${datamodule.transforms}

  checkpoint_path: ''

losses:
  _target_: src.models.metrics.loss.ComputeLosses
  mode: smpl
  loss_dict:
    l_dummy: 1
    l1_data: 1
    #l_perplexity: 0.0
    #l_entropy: 0.0
  loss_opts:
    loss_feat_type: rfeats

lr_args:
  gen_lr: 0.00008

do_evaluation: true

collate_fn: collate_datastruct_and_text

devices: ${trainer.devices}

defaults:
  - /model/motionencoder/vq_encoder_v3_guo@generator.encoder
  - /model/motiondecoder/vq_decoder_v3_guo@generator.decoder
#  - /model/motionencoder/vq_discriminator_guo@generator.discriminator
  - /model/motionencoder/quantizer_guo@generator.quantizer
  - /model/evaluator@evaluator