dataname: kit-ml
_target_: src.datamodules.humanml_datamodule.HumanMLDataModule

datapath: ${paths.datasets}/Guo-KIT-ML/KIT-ML
splitpath: ${paths.datasets}/Guo-KIT-ML/KIT-ML

# Machine
batch_size: ${batch_size}
num_workers: 0

# Motion
framerate: 12.5
joints_num: 21
dim_pose: 251
max_motion_length: 196
feat_bias: 20      # Guo Layers of GRU
defaults:
  - /datamodule/transforms/humanml_smpl.yaml@transforms
  - sampler: fix_conseq

# Other
tiny: false
progress_bar: true

# Collate_fn
collate_fn: ${model.collate_fn}

# Word_vectorizer etc.
deps: ${paths.deps}

devices: ${trainer.devices}