name: SMPLTransform
ename: smpl

_target_: src.datamodules.datasets.transforms.SMPLTransform

normalization: false

defaults:
  - rots2rfeats: smplvelp
  - rots2joints: smplh
  - joints2jfeats: rifke

rots2rfeats:
  normalization: ${datamodule.transforms.normalization}

joints2jfeats:
  normalization: ${datamodule.transforms.normalization}
